eng_to_pirate = { 
  "hello":"ahoy",
  "I agree":"arrr",
  "buddy":"matey",             
  "monster" : "kraken",
  "food" : "grub",
  "my": "me",
  "to" : "ta",
  "friend": "matey",
  "boy": "laddy",
  "girl": "lassie",
  "stranger": "scurvy dog",
  "cafeteria" : "swill dungeon",
  "where": "whar",
  "is": "be",
  "are" : "be",
  "the": "th'",
  "you": "ye",
  "your" : "yer",
  "old": "salty",
  "there": "yonder",
  "bathroom": "head",
  "kitchen": "galley",
  "stop": "avast",
  "yes": "aye",
  "cheer": "yo-ho-ho",
  "understand": "savvy",
  "money": "gold",
  "treasure": "booty",
  "push": "heave-ho",
  "take": "pillage",
  "principal": "scallywag",
  "sea": "briney deep",
  "vote": "mutiny",
  "lol": "yo ho ho",
  "talk": "parley",
  "quickly": "smartly",
  "captain": "cap'n",
  "teacher" : "wise sage",
  "computer" : "magic box",
  "story" : "tale",
  "stories" : "tales",
  "phone" : "cursed device"
}
